[package]
name = "jgu-typst-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Lukas Schröder <https://github.com/inverted-tree>", "Jerry Ling <https://github.com/Moelf>"]
license = "MIT"
description = "Graduate thesis template for Johannes Gutenberg University Mainz"
repository = "https://github.com/inverted-tree/JGU-Typst-Thesis"
keywords = ["JGU", "JGU Mainz", "graduate", "thesis", "dissertation"]
categories = ["thesis"]

[template]
path = "templates"
entrypoint = "main.typ"
thumbnail = "static/cover.png"
